package app.anoterm.ui.settings

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import android.content.Intent
import android.widget.Toast
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.layout.imePadding
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.compose.material3.AssistChip
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.ExperimentalMaterial3Api
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Scaffold
import androidx.compose.material3.Text
import androidx.compose.material3.TopAppBar
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import app.anoterm.R
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.dp
import androidx.annotation.StringRes
import app.anoterm.AnotermApp
import app.anoterm.data.db.SshKeyEntity
import app.anoterm.ssh.KeyValidator
import java.io.StringWriter
import java.security.KeyPair
import java.security.KeyPairGenerator
import java.security.interfaces.RSAPublicKey
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import org.bouncycastle.jcajce.interfaces.EdDSAPublicKey
import org.bouncycastle.openssl.jcajce.JcaPEMWriter
import org.bouncycastle.crypto.util.OpenSSHPrivateKeyUtil
import org.bouncycastle.crypto.util.PrivateKeyFactory
import org.bouncycastle.util.io.pem.PemObject
import org.bouncycastle.util.io.pem.PemWriter

/** enum は Composable の外にあるので、表示名は文字列ではなくリソース ID で持つ。 */
enum class KeyAlgo(@StringRes val display: Int, val jceName: String) {
  ED25519(R.string.keygen_ed25519, "Ed25519"),
  RSA_4096(R.string.keygen_rsa, "RSA"),
}

@OptIn(ExperimentalMaterial3Api::class)
@Composable
fun SshKeyGenScreen(onBack: () -> Unit) {
  val ctx = LocalContext.current
  val app = remember { AnotermApp.get() }
  val scope = rememberCoroutineScope()
  var algo by remember { mutableStateOf(KeyAlgo.ED25519) }
  // 下の生成処理は Composable スコープの外で走る。文言はここで引いておく。
  val unreadableMessage = stringResource(R.string.keygen_unreadable)
  val generateFailed = stringResource(R.string.keygen_failed)
  var label by remember { mutableStateOf("") }
  var comment by remember { mutableStateOf("") }
  var passphrase by remember { mutableStateOf("") }
  var generated by remember { mutableStateOf<Generated?>(null) }
  var busy by remember { mutableStateOf(false) }
  var error by remember { mutableStateOf<String?>(null) }

  Scaffold(
      topBar = {
        TopAppBar(
            title = { Text(stringResource(R.string.keygen_title)) },
            navigationIcon = {
              IconButton(onClick = onBack) {
                Icon(Icons.AutoMirrored.Filled.ArrowBack, contentDescription = null)
              }
            },
        )
      },
  ) { inner ->
    Column(
        // IME で入力欄が隠れないよう imePadding を当てて verticalScroll を combine。
        modifier =
            Modifier.fillMaxSize()
                .padding(inner)
                .padding(horizontal = 20.dp, vertical = 16.dp)
                .imePadding()
                .verticalScroll(rememberScrollState()),
        verticalArrangement = Arrangement.spacedBy(12.dp),
    ) {
      Text(stringResource(R.string.keygen_type), style = MaterialTheme.typography.titleMedium)
      Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
        KeyAlgo.values().forEach { k ->
          AssistChip(
              onClick = { algo = k },
              label = { Text(stringResource(k.display)) },
              colors =
                  if (algo == k)
                      androidx.compose.material3.AssistChipDefaults.assistChipColors(
                          containerColor = MaterialTheme.colorScheme.primaryContainer,
                      )
                  else androidx.compose.material3.AssistChipDefaults.assistChipColors(),
          )
        }
      }

      OutlinedTextField(
          value = label,
          onValueChange = { label = it },
          label = { Text(stringResource(R.string.keygen_name)) },
          modifier = Modifier.fillMaxWidth(),
      )
      OutlinedTextField(
          value = comment,
          onValueChange = { comment = it },
          label = { Text(stringResource(R.string.keygen_comment)) },
          modifier = Modifier.fillMaxWidth(),
      )
      OutlinedTextField(
          value = passphrase,
          onValueChange = { passphrase = it },
          label = { Text(stringResource(R.string.keygen_passphrase)) },
          modifier = Modifier.fillMaxWidth(),
      )

      Button(
          onClick = {
            busy = true
            error = null
            scope.launch {
              runCatching {
                withContext(Dispatchers.IO) {
                  val g = generateKey(algo, comment.ifBlank { "AnoTerm" }, passphrase)
                  // 生成直後に sshj で読めるかを検証。万一 AnoTerm 側のシリアライズが
                  // 壊れていたら、ここでエラーにして SecretStore に書き込ませない。
                  val v =
                      KeyValidator.validate(
                          g.privatePem.toByteArray(Charsets.UTF_8),
                          passphrase.ifBlank { null },
                      )
                  if (v.isFailure) {
                    throw IllegalStateException(
                        unreadableMessage
                            + (v.exceptionOrNull()?.message ?: "unknown"),
                    )
                  }
                  g
                }
              }
                  .onSuccess { g ->
                    // 秘密鍵を SecretStore に保存し、メタ情報を ssh_keys テーブルに登録。
                    // これで一覧画面や HostEdit の「保存済みの鍵から選ぶ」から参照できる。
                    val secretId =
                        app.secretStore.putPrivateKey(
                            keyBytes = g.privatePem.toByteArray(Charsets.UTF_8),
                            passphrase = passphrase.ifBlank { null },
                        )
                    val algoTag =
                        when (g.algo) {
                          KeyAlgo.ED25519 -> "ed25519"
                          KeyAlgo.RSA_4096 -> "rsa4096"
                        }
                    val effectiveLabel =
                        label.trim().ifBlank { "${algoTag}_${System.currentTimeMillis() / 1000}" }
                    withContext(Dispatchers.IO) {
                      app.database.sshKeyDao().upsert(
                          SshKeyEntity(
                              label = effectiveLabel,
                              algo = algoTag,
                              secretId = secretId,
                              publicSsh = g.publicSsh,
                          ),
                      )
                    }
                    generated = g
                  }
                  .onFailure { error = it.message ?: generateFailed }
              busy = false
            }
          },
          enabled = !busy,
          modifier = Modifier.fillMaxWidth(),
      ) {
        Text(stringResource(if (busy) R.string.keygen_working else R.string.keygen_create))
      }

      error?.let {
        Text(it, color = MaterialTheme.colorScheme.error, style = MaterialTheme.typography.bodyMedium)
      }

      generated?.let { g ->
        HorizontalDivider()
        Text(stringResource(R.string.keygen_done), style = MaterialTheme.typography.titleMedium)
        Text(
            stringResource(R.string.keygen_done_body),
            style = MaterialTheme.typography.bodyMedium,
        )
        Text(
            g.publicSsh,
            style =
                MaterialTheme.typography.bodySmall.copy(
                    fontFamily = FontFamily.Monospace,
                ),
            modifier = Modifier.padding(8.dp),
        )
        Row(
            horizontalArrangement = Arrangement.spacedBy(8.dp),
            verticalAlignment = Alignment.CenterVertically,
        ) {
          Button(onClick = {
            val cm = ctx.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager
            cm.setPrimaryClip(ClipData.newPlainText("ssh public key", g.publicSsh))
            Toast.makeText(ctx, ctx.getString(R.string.keygen_copied), Toast.LENGTH_SHORT).show()
          }) {
            Text(stringResource(R.string.action_copy))
          }
          Button(
              onClick = {
                val i = Intent(Intent.ACTION_SEND).apply {
                  type = "text/plain"
                  putExtra(Intent.EXTRA_SUBJECT, ctx.getString(R.string.keygen_share_subject))
                  putExtra(Intent.EXTRA_TEXT, g.publicSsh)
                }
                ctx.startActivity(Intent.createChooser(i, ctx.getString(R.string.keygen_share_title)))
              },
              colors = ButtonDefaults.outlinedButtonColors(),
          ) {
            Text(stringResource(R.string.action_share))
          }
        }
      }
    }
  }
}

private data class Generated(
    val algo: KeyAlgo,
    val privatePem: String,
    val publicSsh: String,
    val comment: String,
)

private fun generateKey(algo: KeyAlgo, comment: String, passphrase: String): Generated {
  // BouncyCastle でキーペア生成（AnotermApp.onCreate で "BC" provider 登録済）
  val kpg =
      when (algo) {
        KeyAlgo.ED25519 -> KeyPairGenerator.getInstance("Ed25519", "BC")
        KeyAlgo.RSA_4096 ->
            KeyPairGenerator.getInstance("RSA", "BC").apply { initialize(4096) }
      }
  val kp: KeyPair = kpg.generateKeyPair()

  // 秘密鍵のシリアライズ。
  // ・RSA は JcaPEMWriter（PKCS8）で OK。sshj の PKCS8KeyFile が OID rsaEncryption を認識する。
  // ・Ed25519 は sshj 0.40 の PKCS8KeyFile が OID 1.3.101.112 を未サポートなので、
  //   BouncyCastle の OpenSSHPrivateKeyUtil で OpenSSH v1 形式に出力し、
  //   sshj の OpenSSHKeyV1KeyFile 経路で読ませる。
  val privatePem: String =
      when (algo) {
        KeyAlgo.ED25519 -> {
          val keyParams = PrivateKeyFactory.createKey(kp.private.encoded)
          val openSshBytes = OpenSSHPrivateKeyUtil.encodePrivateKey(keyParams)
          val sw = StringWriter()
          PemWriter(sw).use { it.writeObject(PemObject("OPENSSH PRIVATE KEY", openSshBytes)) }
          sw.toString()
        }
        KeyAlgo.RSA_4096 -> {
          val sw = StringWriter()
          JcaPEMWriter(sw).use { it.writeObject(kp) }
          sw.toString()
        }
      }

  // 公開鍵を authorized_keys 形式 (`ssh-rsa AAAA... comment` または `ssh-ed25519 AAAA... comment`)
  val publicSsh = toOpenSshPublic(kp, algo, comment)
  return Generated(algo, privatePem, publicSsh, comment)
}

/**
 * Java の PublicKey を OpenSSH の authorized_keys 1 行形式 (`ssh-ed25519 <base64> comment`) に変換。
 */
private fun toOpenSshPublic(kp: KeyPair, algo: KeyAlgo, comment: String): String {
  val pub = kp.public
  val kind: String
  val blob: ByteArray
  when (algo) {
    KeyAlgo.ED25519 -> {
      kind = "ssh-ed25519"
      // BC の EdDSAPublicKey から raw 32 bytes を取り出す。
      // 万一 pointEncoding の仕様が将来 BC 側で変わって長さが狂うと、authorized_keys に
      // 書く公開鍵が壊れて SSH 認証が通らなくなる（しかもエラーがサーバ側でしか出ない）
      // のでここで必ずサイズを assert する。
      val edPub = pub as EdDSAPublicKey
      val encoded = edPub.pointEncoding
      check(encoded.size == 32) {
        "Ed25519 public key encoding is ${encoded.size} bytes, expected 32"
      }
      blob = sshWireBytes(listOf(kind.toByteArray(), encoded))
    }
    KeyAlgo.RSA_4096 -> {
      kind = "ssh-rsa"
      val rsa = pub as RSAPublicKey
      val e = rsa.publicExponent.toByteArray()
      val n = rsa.modulus.toByteArray()
      blob = sshWireBytes(listOf(kind.toByteArray(), e, n))
    }
  }
  val b64 = android.util.Base64.encodeToString(blob, android.util.Base64.NO_WRAP)
  return "$kind $b64 $comment"
}

/**
 * SSH wire format: 各要素を `uint32 length + bytes` で連結。
 */
private fun sshWireBytes(parts: List<ByteArray>): ByteArray {
  val total = parts.sumOf { 4 + it.size }
  val out = ByteArray(total)
  var i = 0
  for (b in parts) {
    out[i] = (b.size ushr 24 and 0xFF).toByte()
    out[i + 1] = (b.size ushr 16 and 0xFF).toByte()
    out[i + 2] = (b.size ushr 8 and 0xFF).toByte()
    out[i + 3] = (b.size and 0xFF).toByte()
    System.arraycopy(b, 0, out, i + 4, b.size)
    i += 4 + b.size
  }
  return out
}
